{
 "title": "HTTP Responses",
 "time": { "from": "2022-10-10T09:00:45.958Z", "to": "2022-10-10T21:00:45.958Z" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Backend-Merger HTTP Total Response",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_request_operations_merger_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend-Merger HTTP 2** Response",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_request_operations_merger_success_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend-Merger HTTP 4** and 5** Response",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_request_operations_merger_error_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend-Rotator HTTP Total Response",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_request_operations_rotator_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend-Rotator HTTP 2** Response",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_request_operations_rotator_success_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend-Rotator HTTP 4** and 5** Response",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_request_operations_rotator_error_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend HTTP Total Response",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_request_operations_frontend_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend HTTP 2** Response",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_request_operations_frontend_success_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend HTTP 4** and 5** Response",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_request_operations_frontend_error_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}