{
 "title": "main dashboard",
 "time": { "from": "2022-10-08T13:01:40.446Z", "to": "2022-10-08T13:11:07.500Z" },
 "panels": [
  {
   "title": "Total operations PDF-Editor/backend-merge",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_request_operations_total{job=\"backend-merge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend-merge HTTP 2**",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_request_operations_success_total{job=\"backend-merge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend-merge HTTP 4** and 5**",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_request_operations_error_total{job=\"backend-merge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container memory usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container=\"pdf-editor\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU usage (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"pdf-editor-ns\",container=\"pdf-editor\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}