{
 "title": "System Usage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total CPU usage (seconds) ",
   "type": "timeseries",
   "description": "all p",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"pdf-editor-ns\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"pdf-editor-ns\"}/(1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Active Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "node_nodejs_active_resources", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Frontend Total Active Handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "node_nodejs_active_handles_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Total Active Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "node_nodejs_active_requests_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}